# Generated by Django 2.0.5 on 2018-06-20 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180619_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
