# Generated by Django 2.0.5 on 2018-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180619_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='The last name of the author.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text="Enter the book's title", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='The date this book is due back (if checked out).', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1, null=True),
        ),
    ]
